# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ZhimuPy',
                'doc_host': 'https://LifeWorks.github.io',
                'git_url': 'https://github.com/LifeWorks/ZhimuPy',
                'lib_path': 'ZhimuPy'},
  'syms': {'ZhimuPy.core': {'ZhimuPy.core.foo': ('core.html#foo', 'ZhimuPy/core.py')}}}
